alias la="ls -a"
alias gedit="gedit 2>/dev/null "
alias jshell='/usr/lib/jvm/java-12-openjdk/bin/jshell'
alias e="echo"
alias refresh=" sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches'"
alias cd3="cd ../../../"
alias hex2asci="xxd -r -p"
alias httpserver="python2 -m SimpleHTTPServer 8000"
alias gdb="gdb -q"
alias range="seq"
alias time="date  +'%I:%M %p'"
alias c="clear"
alias bri2="sudo nvim /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight/brightness"
alias lol="ls -loh"
alias bri="sudo nvim /sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-1/intel_backlight/brightness"
alias wifi="nmcli d wifi list"
alias dc="steghide extract -sf"
alias hakai="shred -n 5 -u -v -z -f "
alias clr="clear"
alias cler="clear"
alias xcp="xclip -selection c -o"
alias servers="systemctl status httpd mariadb;nmap -sT localhost"
alias s="sudo"
alias hiddenfiles="ls -d .!(|.)"
alias usbwrite="sudo dd bs=512M if=file.iso of=/dev/sdX"
alias o.="xdg-open . "
alias ungz="gunzip -k "
alias unbz="bzip2 -dk "
alias r="cd ~/.recycle"
alias ports='netstat -tulanp'
alias grep="grep -ia --color=auto"
alias maek='make'
alias du='du -ch'
alias df='df -h'
alias onn='sudo -su awcator reboot'
alias off="poweroff"
alias incognito='export HISTFILE=/dev/null'
alias ..="cd .."
alias h="history"
alias untar='tar -xvf'
alias o="xdg-open $1"
alias xc='xclip -selection clipboard -i ' 
alias ok="ping google.com"
alias cls="clear"
alias pacman="sudo pacman"
alias cd..="cd .."
alias l="ls"
alias ll="ls -lh"
alias lla="ls -lha"
alias rm="mv -t ~/.recycle -f "
alias vi="nvim -O"
alias cd2="cd ../../"
alias su="sudo su"
alias x="exit"
alias mysql='mycli -u root -p dev' 
alias sql='mycli -u root -p dev -D rhythm' 
alias sudo='sudo '
alias whomai='whoami'
