Section "OutputClass"
    Identifier "intel"
    MatchDriver "i915"
    Driver "modesetting"
EndSection

Section "OutputClass"
    Identifier "nvidia"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "AllowEmptyInitialConfiguration"
    Option "ForceFullCompositionPipeline" "on"
    Option "AllowIndirectGLXProtocol" "off"
    Option "TripleBuffer" "on"
    Option "PrimaryGPU" "yes"
    Option "ConnectedMonitor" "DFP-0, DFP-1"
    Option "CustomEDID" "DFP-1:/etc/X11/edid-virtual.bin"
    Option "ModeValidation" "DFP-1: AllowNonEdidModes"
    ModulePath "/usr/lib/nvidia/xorg"
    ModulePath "/usr/lib/xorg/modules"
EndSection
