DEL run "rm" "${path}"; playlist-next
Ctrl+LEFT playlist-prev         # Ctrl + Left arrow (common in some setups)
Ctrl+RIGHT playlist-next         # Ctrl + Left arrow (common in some setups)

UP    add volume +2
DOWN  add volume -2
